spring:
  application:
    name: credit-score-service-client
  profiles:
    active: local

server:
  port: ${SERVER_PORT:8082}
  servlet:
    context-path: ${CONTEXT_PATH:/credit-score-service-client}